/**
 * @todo Batch request search for tracker
 * @todo Insider buying
 *
 */

export interface ICustomTableKeys {}

export interface IFundamentals {
  date: string;
  symbol: string;
  reportedCurrency: string;
  fillingDate: string;
  acceptedDate: string;
  period: string;
  link: string;
  finalLink: string;
}

export type IncomeStatement = {
  revenue: number | null;
  costOfRevenue: number | null;
  grossProfit: number | null;
  grossProfitRatio: number | null;
  researchAndDevelopmentExpenses: number | null;
  generalAndAdministrativeExpenses: number | null;
  sellingAndMarketingExpenses: number | null;
  otherExpenses: number | null;
  operatingExpenses: number | null;
  costAndExpenses: number | null;
  interestExpense: number | null;
  depreciationAndAmortization: number | null;
  ebitda: number | null;
  ebitdaratio: number | null;
  operatingIncome: number | null;
  operatingIncomeRatio: number | null;
  totalOtherIncomeExpensesNet: number | null;
  incomeBeforeTax: number | null;
  incomeBeforeTaxRatio: number | null;
  incomeTaxExpense: number | null;
  netIncome: number | null;
  netIncomeRatio: number | null;
  eps: number | null;
  epsdiluted: number | null;
  weightedAverageShsOut: number | null;
  weightedAverageShsOutDil: number | null;
} & IFundamentals;

export type BalanceSheet = {
  cashAndCashEquivalents: number | null;
  shortTermInvestments: number | null;
  cashAndShortTermInvestments: number | null;
  netReceivables: number | null;
  inventory: number | null;
  otherCurrentAssets: number | null;
  totalCurrentAssets: number | null;
  propertyPlantEquipmentNet: number | null;
  goodwill: number | null;
  intangibleAssets: number | null;
  goodwillAndIntangibleAssets: number | null;
  longTermInvestments: number | null;
  taxAssets: number | null;
  otherNonCurrentAssets: number | null;
  totalNonCurrentAssets: number | null;
  otherAssets: number | null;
  totalAssets: number | null;
  accountPayables: number | null;
  shortTermDebt: number | null;
  taxPayables: number | null;
  deferredRevenue: number | null;
  otherCurrentLiabilities: number | null;
  totalCurrentLiabilities: number | null;
  longTermDebt: number | null;
  deferredRevenueNonCurrent: number | null;
  deferredTaxLiabilitiesNonCurrent: number | null;
  otherNonCurrentLiabilities: number | null;
  totalNonCurrentLiabilities: number | null;
  otherLiabilities: number | null;
  totalLiabilities: number | null;
  commonStock: number | null;
  retainedEarnings: number | null;
  accumulatedOtherComprehensiveIncomeLoss: number | null;
  othertotalStockholdersEquity: number | null;
  totalStockholdersEquity: number | null;
  totalLiabilitiesAndStockholdersEquity: number | null;
  totalInvestments: number | null;
  totalDebt: number | null;
  netDebt: number | null;
} & IFundamentals;

export type CashFlow = {
  netIncome: number | null;
  depreciationAndAmortization: number | null;
  deferredIncomeTax: number | null;
  stockBasedCompensation: number | null;
  changeInWorkingCapital: number | null;
  accountsReceivables: number | null;
  inventory: number | null;
  accountsPayables: number | null;
  otherWorkingCapital: number | null;
  otherNonCashItems: number | null;
  netCashProvidedByOperatingActivities: number | null;
  investmentsInPropertyPlantAndEquipment: number | null;
  acquisitionsNet: number | null;
  purchasesOfInvestments: number | null;
  salesMaturitiesOfInvestments: number | null;
  otherInvestingActivites: number | null;
  netCashUsedForInvestingActivites: number | null;
  debtRepayment: number | null;
  commonStockIssued: number | null;
  commonStockRepurchased: number | null;
  dividendsPaid: number | null;
  otherFinancingActivites: number | null;
  netCashUsedProvidedByFinancingActivities: number | null;
  effectOfForexChangesOnCash: number | null;
  netChangeInCash: number | null;
  cashAtEndOfPeriod: number | null;
  cashAtBeginningOfPeriod: number | null;
  operatingCashFlow: number | null;
  capitalExpenditure: number | null;
  freeCashFlow: number | null;
} & IFundamentals;

// TTM pick symbol & date from IFundamentals
export type FinRatios = {
  currentRatio: number | null;
  quickRatio: number | null;
  cashRatio: number | null;
  daysOfSalesOutstanding: number | null;
  daysOfInventoryOutstanding: number | null;
  operatingCycle: number | null;
  daysOfPayablesOutstanding: number | null;
  cashConversionCycle: number | null;
  grossProfitMargin: number | null;
  operatingProfitMargin: number | null;
  pretaxProfitMargin: number | null;
  netProfitMargin: number | null;
  effectiveTaxRate: number | null;
  returnOnAssets: number | null;
  returnOnEquity: number | null;
  returnOnCapitalEmployed: number | null;
  netIncomePerEBT: number | null;
  ebtPerEbit: number | null;
  ebitPerRevenue: number | null;
  debtRatio: number | null;
  debtEquityRatio: number | null;
  longTermDebtToCapitalization: number | null;
  totalDebtToCapitalization: number | null;
  interestCoverage: number | null;
  cashFlowToDebtRatio: number | null;
  companyEquityMultiplier: number | null;
  receivablesTurnover: number | null;
  payablesTurnover: number | null;
  inventoryTurnover: number | null;
  fixedAssetTurnover: number | null;
  assetTurnover: number | null;
  operatingCashFlowPerShare: number | null;
  freeCashFlowPerShare: number | null;
  cashPerShare: number | null;
  payoutRatio: number | null;
  operatingCashFlowSalesRatio: number | null;
  freeCashFlowOperatingCashFlowRatio: number | null;
  cashFlowCoverageRatios: number | null;
  shortTermCoverageRatios: number | null;
  capitalExpenditureCoverageRatio: number | null;
  dividendPaidAndCapexCoverageRatio: number | null;
  dividendPayoutRatio: number | null;
  priceBookValueRatio: number | null;
  priceToBookRatio: number | null;
  priceToSalesRatio: number | null;
  priceEarningsRatio: number | null;
  priceToFreeCashFlowsRatio: number | null;
  priceToOperatingCashFlowsRatio: number | null;
  priceCashFlowRatio: number | null;
  priceEarningsToGrowthRatio: number | null;
  priceSalesRatio: number | null;
  dividendYield: number | null;
  enterpriseValueMultiple: number | null;
  priceFairValue: number | null;
} & Pick<IFundamentals, 'symbol' | 'date' | 'period'>;

export type KeyMetrics = {
  revenuePerShareTTM: number | null;
  netIncomePerShareTTM: number | null;
  operatingCashFlowPerShareTTM: number | null;
  freeCashFlowPerShareTTM: number | null;
  cashPerShareTTM: number | null;
  bookValuePerShareTTM: number | null;
  tangibleBookValuePerShareTTM: number | null;
  shareholdersEquityPerShareTTM: number | null;
  interestDebtPerShareTTM: number | null;
  marketCapTTM: number | null;
  enterpriseValueTTM: number | null;
  peRatioTTM: number | null;
  priceToSalesRatioTTM: number | null;
  pocfratioTTM: number | null;
  pfcfRatioTTM: number | null;
  pbRatioTTM: number | null;
  ptbRatioTTM: number | null;
  evToSalesTTM: number | null;
  enterpriseValueOverEBITDATTM: number | null;
  evToOperatingCashFlowTTM: number | null;
  evToFreeCashFlowTTM: number | null;
  earningsYieldTTM: number | null;
  freeCashFlowYieldTTM: number | null;
  debtToEquityTTM: number | null;
  debtToAssetsTTM: number | null;
  netDebtToEBITDATTM: number | null;
  currentRatioTTM: number | null;
  interestCoverageTTM: number | null;
  incomeQualityTTM: number | null;
  dividendYieldTTM: number | null;
  dividendYieldPercentageTTM: number | null;
  payoutRatioTTM: number | null;
  salesGeneralAndAdministrativeToRevenueTTM: number | null;
  researchAndDevelopementToRevenueTTM: number | null;
  intangiblesToTotalAssetsTTM: number | null;
  capexToOperatingCashFlowTTM: number | null;
  capexToRevenueTTM: number | null;
  capexToDepreciationTTM: number | null;
  stockBasedCompensationToRevenueTTM: number | null;
  grahamNumberTTM: number | null;
  roicTTM: number | null;
  returnOnTangibleAssetsTTM: number | null;
  grahamNetNetTTM: number | null;
  workingCapitalTTM: number | null;
  tangibleAssetValueTTM: number | null;
  netCurrentAssetValueTTM: number | null;
  investedCapitalTTM: number | null;
  averageReceivablesTTM: number | null;
  averagePayablesTTM: number | null;
  averageInventoryTTM: number | null;
  daysSalesOutstandingTTM: number | null;
  daysPayablesOutstandingTTM: number | null;
  daysOfInventoryOnHandTTM: number | null;
  receivablesTurnoverTTM: number | null;
  payablesTurnoverTTM: number | null;
  inventoryTurnoverTTM: number | null;
  roeTTM: number | null;
  capexPerShareTTM: number | null;
} & Pick<IFundamentals, 'symbol' | 'date'>;
